Feature/news
shootaa/test01 pull request #2
Opened 2020-03-30 09:25 UTC by shootaa

[やったこと]
news,recruit,contact画面の実装
[やっていないこと]
レスポンシブ機能の実装。

2020-03-31 12:38 UTC, nozomi71 commented on stylesheet.scss
> +    padding-left: 228px;
absolute使った方が早くないですか？

2020-03-31 12:38 UTC, nozomi71 commented on recruit.html
> +    <p>採用情報</p>
これh2ですね

2020-03-31 12:38 UTC, nozomi71 commented on recruit.html
> +                ・オーダーメイド家具の発注 <br />
`li`使わない？

2020-03-31 12:38 UTC, nozomi71 commented on stylesheet.scss
> +  height: 624px;
これ嫌ですね〜…
文字増えた時確実にデザイン崩れます
セルにpadding与えましょう

2020-04-01 05:24 UTC, shootaa commented on stylesheet.scss
> +    padding-left: 228px;
position:absoluteで指定しました。

2020-04-01 05:24 UTC, shootaa commented on recruit.html
> +    <p>採用情報</p>
p→h2タグに変更しました。

2020-04-01 05:30 UTC, shootaa commented on stylesheet.scss
> +  height: 624px;
thとtdにpaddingを当てました。

2020-04-01 05:40 UTC, shootaa commented on recruit.html
> +                ・オーダーメイド家具の発注 <br />
li使いました！

2020-04-01 09:11 UTC, piasoratech requested changes
HTMLのほう構文チェックかけるとまだエラーが出ているのでそれを修正して再提出お願いします！

2020-04-02 08:50 UTC, piasoratech requested changes
構文チェッカーってどれ使われてますか？
まだ私のほうで構文チェックかけたらエラーが出るので確認してもらいたいです。

2020-04-06 10:11 UTC, piasoratech requested changes
全体を通しての指摘ですが、`class`や`id`名にマジックナンバー(xxxx1のようなもの)を使うのは良くないのでやめましょう。
その名前を見ただけでどのような要素なのか判別できるのが理想です。
その部分の修正をお願いします！

2020-04-08 04:59 UTC, yusaku-inamura requested changes
レビューしました!
少し文書構造に指摘入れてますが、全体的にはいい感じだと思います。
コメント確認して修正お願いします 👍

2020-04-08 04:59 UTC, yusaku-inamura commented on contact.html
> +    <title>wev＿site_html_css</title>
テスト課題なのでそこまで過敏になる必要もないのですが、titleには各ページの内容を表す文字通りのタイトルを入れておくのが良いですね。
SEO的な観点でも結構重要な要素なので、ちゃんと設定しておく癖をつけておくことをお勧めします 👍

2020-04-08 04:59 UTC, yusaku-inamura commented on contact.html
> +            <img class="header-left" src="quelcode_task01/home_top/logo_header/logo_header.png" alt="HTMLCSS" />
alt属性についても極力画像の補足となるようなテキストを入れておくのが良いです。
こちらもSEO的観点の話なのですが、いわゆる検索エンジン用のwebクローラには画像の情報が視覚的に取り込めないため、alt属性の値を読み込むからですね。
その他スクリーンリーダの読み上げ時にも活用される等、単なる画像リソースが取得できない場合の代替テキスト以外にも多くの役目がありますので少し調べてみてください。

今回は課題用のダミーサイトのためそこまで深く考えなくても大丈夫ですので、少しだけ考えてみましょう。

2020-04-08 04:59 UTC, yusaku-inamura commented on contact.html
> +    <div class="top-container_contact">
なにか明確なルールがないのであれば、クラス名にハイフン `-` とアンダースコア `_` をごちゃ混ぜで使うべきではないですね。
ここはいわゆるケースと呼ばれる、命名時の規則とでもいうべきものに乗っ取るのがお勧めです。
ケバブケースとかスネークケースとかで調べてみてください。
どれを選ぶかは宗教論争的なところがありますが、今まで僕がみてきた中では比較的ケバブケースが多いかなと思います。

2020-04-08 04:59 UTC, yusaku-inamura commented on contact.html
> +        <h2>お問い合わせ</h2>
なんかこっから下インデントおかしくないですかね?

2020-04-08 04:59 UTC, yusaku-inamura commented on contact.html
> +            <li><a class="footer-home">HOME</a></li>
aタグにhref属性がないですね。
もし意図的であれば理由を教えてもらえると。
(ちなみにHTML5より前はaタグにhref属性は必須だったのでその指摘しようとしたのですが、HTML5から必須じゃなくなっているというのを今調べて知りました 😮 )

2020-04-08 04:59 UTC, yusaku-inamura commented on index.html
> +      <a href="#">view more</a>
ここだけではなく他の同様の要素でも同じことが言えますが、XDと見た目が明確に違ってしまっていますね。
少し画面XDと見比べてみてください。

2020-04-08 04:59 UTC, yusaku-inamura commented on news.html
> +            <div class="test1"></div>
この要素必要ですか?

2020-04-08 04:59 UTC, yusaku-inamura commented on recruit.html
> +        </ul>
定義リストの装飾をCSSで外してからここで改めて文章として「・」をつけてるのって理由がありますか?
そもそも装飾を外さなければ文章に余計な文字を入れずに気がしますね。

2020-04-08 04:59 UTC, yusaku-inamura commented on recruit.html
> +        ・オーダーメイド家具の製作 <br />
仕事内容の方で使っているのにここにulを使っていない理由はなんですかね?

2020-04-08 04:59 UTC, yusaku-inamura commented on recruit.html
> +        <span> 仕事内容 </span><br />
ここら辺spanだと意味のない要素になってしまいますね。
ちょっと難しいですが、今回の場合見出しと捉えてhタグ使っても良さそうです。

2020-04-08 06:35 UTC, shootaa commented on contact.html
> +    <title>wev＿site_html_css</title>
なるほど！
タイトルとして入力しました。

2020-04-08 06:40 UTC, shootaa commented on contact.html
> +            <img class="header-left" src="quelcode_task01/home_top/logo_header/logo_header.png" alt="HTMLCSS" />
承知しました！
考えて記載してみました！

2020-04-08 06:44 UTC, shootaa commented on contact.html
> +    <div class="top-container_contact">
ケバブケースで統一しました！

2020-04-08 06:47 UTC, shootaa commented on contact.html
> +        <h2>お問い合わせ</h2>
インデント整えました！

2020-04-08 06:51 UTC, shootaa commented on contact.html
> +            <li><a class="footer-home">HOME</a></li>
XDだとフッターから画面遷移できないのでhrefはつけない方がよいかと思い省略していました！
つけない意味もないかなとは思うのですが、今回の場合つけた方が良いでしょうか？

2020-04-08 07:19 UTC, shootaa commented on index.html
> +      <a href="#">view more</a>
矢印マークを追記しました！

2020-04-08 07:21 UTC, shootaa commented on news.html
> +            <div class="test1"></div>
<div class="test1"></div>不要なので、消しました！

2020-04-08 07:28 UTC, shootaa commented on recruit.html
> +        </ul>
消し忘れていました！
ヘッダーでlist-style:noneとしているので、こちらではlist-style:discとしました

2020-04-08 07:29 UTC, shootaa commented on recruit.html
> +        ・オーダーメイド家具の製作 <br />
こっちだけ変更するのを忘れていました！
上記同様に変更しました！

2020-04-08 07:38 UTC, shootaa commented on recruit.html
> +        <span> 仕事内容 </span><br />
h2タグを使用するようにしました！

2020-04-09 08:49 UTC, piasoratech requested changes
コメントしました！

2020-04-09 08:49 UTC, piasoratech commented on recruit.html
> +        <h2> 仕事内容 </h2><br />
ここ見出しかといわれると微妙なので`p`タグ使ってスタイルつけましょうか
`table`内の同じような場所も同様です！

2020-04-09 08:49 UTC, piasoratech commented on recruit.html
> +        週３〜5日
使うなら`p`タグですかね

2020-04-09 08:49 UTC, piasoratech commented on recruit.html
> +          <li>商品管理 ・オーダーメイド家具の相談</li>
ここお手本と異なりません？

2020-04-10 00:45 UTC, shootaa commented on recruit.html
> +        <h2> 仕事内容 </h2><br />
h2→pタグにしました！

2020-04-10 00:46 UTC, shootaa commented on recruit.html
> +        週３〜5日
pタグにしました！

2020-04-10 01:08 UTC, shootaa commented on recruit.html
> +          <li>商品管理 ・オーダーメイド家具の相談</li>
・オーダーメイド家具の相談の部分修正しました！

2020-04-10 03:30 UTC, piasoratech commented on recruit.html
> +        <h2> 仕事内容 </h2><br />
あ、そこは稲村さんとも話したうえで指摘をしているので、今回の指摘に合わせていただければ大丈夫です！

2020-04-10 03:32 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-10 03:32 UTC, piasoratech commented on recruit.html
> +        週３〜5日</p>
ここの数字お手本だと全半角混ざってるんですが、お手本のミスなので半角に修正をお願いします。

2020-04-10 03:32 UTC, piasoratech commented on recruit.html
> +          週３〜5日</p>
ここも半角でお願いします

2020-04-10 03:46 UTC, shootaa commented on recruit.html
> +        <h2> 仕事内容 </h2><br />
承知しました！

2020-04-10 04:04 UTC, shootaa commented on recruit.html
> +        週３〜5日</p>
e195928
7edf7f5
このコミットで対応しました！

2020-04-10 04:04 UTC, shootaa commented on recruit.html
> +          週３〜5日</p>
e195928
7edf7f5
このコミットで対応しました！

2020-04-10 06:01 UTC, piasoratech requested changes
まだ見つけてしまったので、確認をお願いします！
他の部分も同じようなところあると思うので合わせて修正しましょう！

2020-04-10 06:01 UTC, piasoratech commented on recruit.html
> +        <p class="title"> 時給 </p><br />
`p`タグの後って改行されるので`br`は…

2020-04-10 06:11 UTC, shootaa commented on recruit.html
> +        <p class="title"> 時給 </p><br />
89c539a9e04ebb0b89788a59b99eb9a1c8f890de

上記コミットで対応。
冗長でした、、、
brタグ消去しました。また、<br/>を<br>に統一しました。

2020-04-10 06:43 UTC, piasoratech approved these changes
OKです！

2020-04-10 06:53 UTC, Yuzunoha approved these changes
ユズノハ的にもOKです！！
きょう居る講師が全員OKしたのでマージしちゃってください！！！

2020-04-10 07:26 UTC, merged