homeメニューのレスポンシブ対応
shootaa/test01 pull request #3
Opened 2020-04-13 08:54 UTC by shootaa

・やったこと
homeメニューのレスポンシブ対応、ハンバーガーメニュー
・やってないこと
他画面のレスポンシブ対応、ハンバーガーメニュー

2020-04-13 09:02 UTC, piasoratech requested changes
・問い合わせフォームの「お問い合わせ内容」の高さがちがいます
![image](https://user-images.githubusercontent.com/57445698/79108207-cf11fc80-7db0-11ea-89b4-1d5b8b8b93cc.png)
・コピーライトがないです。
![image](https://user-images.githubusercontent.com/57445698/79108264-ed77f800-7db0-11ea-9d5d-c6a10685d454.png)

2020-04-13 10:12 UTC, shootaa commented
> ・問い合わせフォームの「お問い合わせ内容」の高さがちがいます
> ![image](https://user-images.githubusercontent.com/57445698/79108207-cf11fc80-7db0-11ea-89b4-1d5b8b8b93cc.png)
> ・コピーライトがないです。
> ![image](https://user-images.githubusercontent.com/57445698/79108264-ed77f800-7db0-11ea-9d5d-c6a10685d454.png)

ea043b71fb875cae00ddba3df37c46031585de2c
上記コミットで対応しました！

2020-04-14 03:01 UTC, piasoratech requested changes
・フォントがここだけ違ったりしますか？
![image](https://user-images.githubusercontent.com/57445698/79181614-b86ab480-7e47-11ea-9a5f-4389df9e42a5.png)
・謎の線が入っちゃってます
![image](https://user-images.githubusercontent.com/57445698/79181666-de905480-7e47-11ea-85c1-561a1c3e20f3.png)

2020-04-14 07:31 UTC, shootaa commented
6791367bc4de8f518e9f11bbd32278080945854d
上記コミットで対応しました。
フォント指定しました。
コピーライトはfooter-containerのdivの中に入れました。

2020-04-14 07:47 UTC, piasoratech approved these changes
良いかと！

2020-04-14 23:23 UTC, merged